pdf:
	latexmk -pdf -interaction=nonstopmode -halt-on-error to_notch_a_stone_with_six_birds.tex
	latexpand to_notch_a_stone_with_six_birds.tex > to_notch_a_stone_with_six_birds_flattened.tex

clean:
	latexmk -C
